### ISSUE TITLE
_tileFunction is global

### ISSUE THREAD

**Issue by allartk** [ismyrnow/Leaflet.functionaltilelayer#2]
A great plugin! But _tileFunction is made global in initialize, limiting the number of layers of this type to just one.

I replaced it with this._tileFunction = tileFunction;

idem on line 33 return this._tileFunction(view);

**Comment by ismyrnow** [comment]
Thanks for the feedback. I will get this fix in.

**Comment by ismyrnow** [comment]
Fixed in f4f02f9bcf1242a51784f097d286df86eb4073b6.
