### ISSUE TITLE
Leaflet V8-dev breaking FunctionalTileLayer

### ISSUE THREAD

**Issue by DrYSG** [ismyrnow/Leaflet.functionaltilelayer#5]
It seems that some refactoring is going on in the latest beta that breaks the FunctionalTileLayer.

@DrYSG

![image](https://f.cloud.github.com/assets/2865368/1802977/09ef858a-6c0f-11e3-9e1e-2986a45cbdd6.png)

**Comment by DrYSG** [comment]
The issue is only happening with deferred gets of tile images. I have a demo at:

http://codepen.io/DrYSG/pen/Lsavw

In the demo I have a path that is commented that in the functional tile layer function, that just returns the url for the image. That works fine. But I the active part (2 lines with comments at the end that say deferred) goes and uses the XHR2 library to fetch the actual image url as a blob, and then returns the resolved imageurl to the blob. That fails.

**Comment by DrYSG** [comment]
The V8 Leaflet code changed dramatically for creating TileLayers and handling them. I created a new plug I called deferLayer.

It still has an issue with maxNaturalZoom. You can see the write-up about it here: https://github.com/Leaflet/Leaflet/issues/2334

**Comment by ismyrnow** [comment]
I just realized that by "V8" you means Leaflet 0.8-dev. I created a branch called `leaflet-0.8` which contains the updated plugin and examples that support the dev version.

It sounds like you may have worked around the issue, though. As Vladimir suggested [here](https://github.com/Leaflet/Leaflet/issues/2334#issuecomment-31201387), rolling your own plugin for this is really trivial now, thanks to the recent refactorings.
